# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-20 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Miners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('selected_gpus', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('gpus', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('fanrpm', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('fanpercent', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('hash', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('miner', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('miner_hashes', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('hwerrors', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('gpu_models', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('bioses', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('default_core', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('default_mem', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('vramsize', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('core', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('mem', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('memstates', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('meminfo', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('voltage', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('overheatedgpu', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('throttled', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('powertune', models.CharField(blank=True, default=None, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_data', models.CharField(blank=True, default=None, max_length=256, null=True)),
            ],
        ),
    ]
