# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-20 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rx_kbps', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('tx_kbps', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('kernel', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('boot_mode', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('uptime', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('mac', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('hostname', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('rack_loc', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('ip', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('mobo', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('lan_chip', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('load', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('ram', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('cpu_temp', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('rofs', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('drive_name', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('freespace', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('temp', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('version', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('miner_secs', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('adl_error', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('proxy_problem', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('updating', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('connected_displays', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('resolution', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('gethelp', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('config_error', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('send_remote', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('autorebooted', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('status', models.CharField(blank=True, default=None, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Miner_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defunct', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('off', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('allowed', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('overheat', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('pool_info', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('pool', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('miner_version', models.CharField(blank=True, default=None, max_length=256, null=True)),
            ],
        ),
    ]
