# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-20 23:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_hosts_miner_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='miner_info',
            name='gpu',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.Miners'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='miners',
            name='host',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.Hosts'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='inputdata',
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
    ]
