# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-23 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20170523_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='miner_info',
            name='cpu_name',
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
    ]
