# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-23 16:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_miner_info_cpu_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='miner_info',
            old_name='gpu_models',
            new_name='gpumodels',
        ),
    ]
