# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-24 03:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20170524_0326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miner_info',
            name='host',
            field=models.CharField(blank=True, default=None, max_length=256, primary_key=True, serialize=False, unique=True),
        ),
    ]
